config:
  azure-native:location: westeurope
  tixtalk:prefix: godotfest
  tixtalk:environment: dev
  tixtalk:vmSize: Standard_B2s
  tixtalk:pretixImageTag: stable
  tixtalk:pretalxImageTag: latest
  tixtalk:mailFrom: noreply@godotfest.com
  # Required — set before running `pulumi up`:

  tixtalk:domain: godotfest.com
  tixtalk:sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCXKsPDUWpQHp8W/Up6FdAnlnCk5atme5Nzdg5Tms3vpDjV01xzD4udpibWVm3JGfNqw8B4xzDIC+hSZAcgPVlehyoX/kyNz4TSQtHLEaVsuHeRxzcnB5NEW1fVqmYxI+XayduLG64HkvdlVz/8GmEtuoWB7pmc8QdKaSGBchkw7wA2h1eIgL1l7huy5xisOvTALIZqKUmqu3uYVSRcbfqT6PASwzlYVbhOoJFW3jj50lkYOv3euhAJOjpx9PzntJJBnvHKTz1ldYiALnEJGvNChAcqclNcBh+mI7Sj9kfyW9Ofh4sQN7aydMwz32uRfYxqUJ6lXz7tZxp61ilwsG5C9aFPsXkeq7bw9/cRMg3Sv2qAvGkNXCXS4BF8vkMRF0CTVcuY0bHX3B8PsDfmgKe155ATTNT3qXITY+wnVfl0tz45ofH7JAJlA+UHEkhh8H31zSYyWEKbsnI4tBKfKpIr4nsR6sG5dObC4UEGb/gstfbj6kCCRmRDVax259GltRBtGUbuSNhbxqeGpWcTHLgHrvOfBRo09yFPEc/utCvCl+XpfPehUwyzEbigy8CgNqOzRCgjOaoDQpoQyF/+3cRhnWiW1fik64sS+l3f0jEFRTaLZ+a0oYr3SiebEJpgsyPYwdy5bQ4AmpUjgw5z4EbcWGIUXIQzySft7/E/8hFnyw==
  tixtalk:smtpHost: smtp.azurecomm.net
  tixtalk:smtpPort: "587"
  tixtalk:smtpUser: godotfest-web-communication-services-eu.293a0707-6a9d-4f84-9199-c38446763d56.b9b56bc4-19cb-4686-b32d-ec36a6b2baad
  tixtalk:smtpPassword:
    secure: AAABAOZkxeOJVSFA448OXkqbjW6P84XsrFoZUzM3n0vi8zkcfzc/FfothksEF+5P4mHR1ktLLrPNe3jmdpWrUds5xzq6sZNQ
  tixtalk:cloudflareApiToken:
    secure: AAABAALcFhUMEkpH+UqPMU6j5jEpBRgEXl+++/Em7nwJ+JRh86OclGDVIJyGwvS5PIioOtRa1oPJsgX1569Tnf1kLd3dVUZtiqmdC0QhgqJrcECtOA==
  tixtalk:cloudflareZoneId: 3191caf42094e04b63439d70094f4b26
  tixtalk:cloudflareDnsChallenge: "true"
  tixtalk:adminEmail: johannes@godotfest.com
  tixtalk:useAzureMail: "true"
  tixtalk:acsUseCustomDomain: "true"