using Pulumi;
using Pulumi.AzureAD;
using Pulumi.AzureNative.Authorization;
using Pulumi.AzureNative.Communication;
using Pulumi.AzureNative.Resources;
using Guid = System.Guid;

namespace PreTalxTix.Infra.Infrastructure;

/// <summary>
/// Output record for ACS Email resources.
/// </summary>
public record AzureCommunicationResult
{
    public required Output<string> SmtpHost { get; init; }
    public required Output<string> SmtpUser { get; init; }
    public required Output<string> SmtpPassword { get; init; }
    public required Output<string> MailFrom { get; init; }
    public required Output<string> EmailServiceId { get; init; }
    /// <summary>
    /// DNS verification records needed for custom domains (JSON serialized).
    /// Only populated when using a custom domain.
    /// </summary>
    public Output<string>? VerificationRecords { get; init; }
}

/// <summary>
/// Arguments for creating the ACS stack.
/// </summary>
public record AzureCommunicationArgs
{
    public required string Prefix { get; init; }
    public required string Domain { get; init; }
    public required ResourceGroup ResourceGroup { get; init; }
    public bool UseCustomDomain { get; init; } = false;
}

/// <summary>
/// Creates Azure Communication Services with Email capability.
/// Supports both Azure-managed domains and custom domains (when Cloudflare is configured).
/// </summary>
public static class AzureCommunicationStack
{
    // Email Communication Services Contributor role definition ID
    private const string EmailContributorRoleId = "e9b2a056-6382-4fac-9b8f-8c42da5f192d";

    public static AzureCommunicationResult Create(AzureCommunicationArgs args)
    {
        // 1. Create the Email Service first (domains belong to email service)
        var emailService = new EmailService($"{args.Prefix}-email", new EmailServiceArgs
        {
            EmailServiceName = $"{args.Prefix}-email",
            ResourceGroupName = args.ResourceGroup.Name,
            DataLocation = "United States",
            Location = "Global",
            Tags = { { "managed-by", "pulumi" } },
        });

        // 2. Create Domain - Azure-managed or custom
        Output<string> mailFrom;
        Output<string>? verificationRecords = null;
        Domain domain;

        if (args.UseCustomDomain)
        {
            // Custom domain - DNS records will be created via cloud-init + Cloudflare API
            domain = new Domain($"{args.Prefix}-email-domain", new DomainArgs
            {
                DomainName = args.Domain,
                EmailServiceName = emailService.Name,
                ResourceGroupName = args.ResourceGroup.Name,
                DomainManagement = DomainManagement.CustomerManaged,
                Location = "Global",
                UserEngagementTracking = UserEngagementTracking.Disabled,
            });

            mailFrom = Output.Create($"noreply@{args.Domain}");
            
            // Export verification records for DNS setup
            verificationRecords = domain.VerificationRecords.Apply(vr =>
            {
                var records = new System.Text.Json.Nodes.JsonObject();
                if (vr?.Domain != null)
                    records["domain"] = System.Text.Json.Nodes.JsonNode.Parse(
                        $"{{\"type\":\"{vr.Domain.Type}\",\"name\":\"{vr.Domain.Name}\",\"value\":\"{vr.Domain.Value}\",\"ttl\":{vr.Domain.Ttl}}}");
                if (vr?.SPF != null)
                    records["spf"] = System.Text.Json.Nodes.JsonNode.Parse(
                        $"{{\"type\":\"{vr.SPF.Type}\",\"name\":\"{vr.SPF.Name}\",\"value\":\"{vr.SPF.Value}\",\"ttl\":{vr.SPF.Ttl}}}");
                if (vr?.DKIM != null)
                    records["dkim"] = System.Text.Json.Nodes.JsonNode.Parse(
                        $"{{\"type\":\"{vr.DKIM.Type}\",\"name\":\"{vr.DKIM.Name}\",\"value\":\"{vr.DKIM.Value}\",\"ttl\":{vr.DKIM.Ttl}}}");
                if (vr?.DKIM2 != null)
                    records["dkim2"] = System.Text.Json.Nodes.JsonNode.Parse(
                        $"{{\"type\":\"{vr.DKIM2.Type}\",\"name\":\"{vr.DKIM2.Name}\",\"value\":\"{vr.DKIM2.Value}\",\"ttl\":{vr.DKIM2.Ttl}}}");
                return records.ToJsonString();
            });
        }
        else
        {
            // Azure-managed domain (xxxxxxxx.azurecomm.net)
            domain = new Domain($"{args.Prefix}-email-domain", new DomainArgs
            {
                DomainName = "AzureManagedDomain",
                EmailServiceName = emailService.Name,
                ResourceGroupName = args.ResourceGroup.Name,
                DomainManagement = DomainManagement.AzureManaged,
                Location = "Global",
                UserEngagementTracking = UserEngagementTracking.Disabled,
            });

            // For Azure-managed domains, the actual domain name is generated by Azure
            mailFrom = domain.MailFromSenderDomain.Apply(d => $"noreply@{d}");
        }

        // 3. Create a sender username for 'noreply'
        var senderUsername = new SenderUsername($"{args.Prefix}-noreply", new SenderUsernameArgs
        {
            SenderUsername = "noreply",
            Username = "noreply",
            DisplayName = "No Reply",
            DomainName = domain.Name,
            EmailServiceName = emailService.Name,
            ResourceGroupName = args.ResourceGroup.Name,
        });

        // 4. Create the Communication Service and link the domain
        var communicationService = new CommunicationService($"{args.Prefix}-acs", new CommunicationServiceArgs
        {
            CommunicationServiceName = $"{args.Prefix}-acs",
            ResourceGroupName = args.ResourceGroup.Name,
            DataLocation = "United States",
            Location = "Global",
            LinkedDomains = { domain.Id },
            Tags = { { "managed-by", "pulumi" } },
        });

        // 5. Create Entra ID Application for SMTP authentication
        var app = new Application($"{args.Prefix}-email-app", new ApplicationArgs
        {
            DisplayName = $"{args.Prefix}-email-smtp",
        });

        // 6. Create Service Principal for the application
        var servicePrincipal = new ServicePrincipal($"{args.Prefix}-email-sp", new ServicePrincipalArgs
        {
            ClientId = app.ClientId,
        });

        // 7. Create client secret (password) for SMTP authentication
        var appPassword = new ApplicationPassword($"{args.Prefix}-email-secret", new ApplicationPasswordArgs
        {
            ApplicationId = app.Id,
            DisplayName = "SMTP Auth Secret",
            EndDateRelative = "8760h", // 1 year
        });

        // 8. Get current client config for subscription/tenant info
        var clientConfig = Pulumi.AzureNative.Authorization.GetClientConfig.Invoke();

        // 9. Assign Email Contributor role to the service principal on the Email Service
        var roleAssignment = new RoleAssignment($"{args.Prefix}-email-role", new RoleAssignmentArgs
        {
            RoleAssignmentName = Guid.NewGuid().ToString(),
            Scope = emailService.Id,
            PrincipalId = servicePrincipal.ObjectId,
            PrincipalType = PrincipalType.ServicePrincipal,
            RoleDefinitionId = clientConfig.Apply(c => 
                $"/subscriptions/{c.SubscriptionId}/providers/Microsoft.Authorization/roleDefinitions/{EmailContributorRoleId}"),
        });

        // 10. Build SMTP credentials
        // Username format: {communicationServiceName}.{applicationId}.{tenantId}
        var smtpUser = Output.Tuple(communicationService.Name, app.ClientId, clientConfig)
            .Apply(t => $"{t.Item1}.{t.Item2}.{t.Item3.TenantId}");

        return new AzureCommunicationResult
        {
            SmtpHost = Output.Create("smtp.azurecomm.net"),
            SmtpUser = smtpUser,
            SmtpPassword = appPassword.Value,
            MailFrom = mailFrom,
            EmailServiceId = emailService.Id,
            VerificationRecords = verificationRecords,
        };
    }
}
